/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package std_verwaltung;
import java.sql.*;
import java.lang.*; // if vectors are needed
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user1
 */
public class Jframe_ADMIN extends javax.swing.JFrame {

    private static Connection connect = null; 
    private static Statement statement = null; //objekt,damit sql befehle geliefert wird.
    private PreparedStatement preparedStatement = null;
    private ResultSet resultSet = null; //beinhaltet data, das aus database abgerufen wird. 
    private static String url = "jdbc:mysql://localhost:3306/software_project"; //driver url(localhost,weil db sich in gleichen PC befindet)
    private static String username = "root";
    private static String password = "123456";
    public  String connection_sucessfull = "DB Connection is sucessfull" ;
    
    public Jframe_ADMIN() {
        initComponents();
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_con_state = new javax.swing.JLabel();
        jButton_check_con = new javax.swing.JButton();
        jInternalFrame_LVA_hinzufügen = new javax.swing.JInternalFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jComboBox_gruppe_auswahl = new javax.swing.JComboBox<>();
        jComboBox_dozent_name = new javax.swing.JComboBox<>();
        jTextField_lva_name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTable_list_lva_delete = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_list_lva1 = new javax.swing.JTable();
        jButton_lva_löschen = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_list_lva = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel_gesamt_lehrstunde = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_gesamte_lehrstunde = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jToggleButton_loesche_alle_daten = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADMIN PAGE");
        setPreferredSize(new java.awt.Dimension(885, 519));

        jButton_check_con.setText("Check DB Connection ");
        jButton_check_con.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_check_conActionPerformed(evt);
            }
        });

        jInternalFrame_LVA_hinzufügen.setVisible(false);

        javax.swing.GroupLayout jInternalFrame_LVA_hinzufügenLayout = new javax.swing.GroupLayout(jInternalFrame_LVA_hinzufügen.getContentPane());
        jInternalFrame_LVA_hinzufügen.getContentPane().setLayout(jInternalFrame_LVA_hinzufügenLayout);
        jInternalFrame_LVA_hinzufügenLayout.setHorizontalGroup(
            jInternalFrame_LVA_hinzufügenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame_LVA_hinzufügenLayout.setVerticalGroup(
            jInternalFrame_LVA_hinzufügenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPane1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTabbedPane1KeyPressed(evt);
            }
        });

        jComboBox_gruppe_auswahl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_gruppe_auswahlActionPerformed(evt);
            }
        });

        jComboBox_dozent_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_dozent_nameActionPerformed(evt);
            }
        });

        jTextField_lva_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_lva_nameActionPerformed(evt);
            }
        });

        jLabel1.setText("NAME DER LVA");

        jLabel2.setText("DOZENT DER LVA");

        jLabel3.setText("GRUPPE DER LVA");

        jButton2.setText("LVA Hinzufügen");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(131, 131, 131)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox_gruppe_auswahl, 0, 94, Short.MAX_VALUE)
                    .addComponent(jTextField_lva_name)
                    .addComponent(jComboBox_dozent_name, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(343, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_lva_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox_dozent_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_gruppe_auswahl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(43, 43, 43)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("LVA Hinzufügen", jPanel2);

        jTable_list_lva1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "LVA Name", "LVA ID", "LVA Gruppe ", "Dozent Name"
            }
        ));
        jScrollPane2.setViewportView(jTable_list_lva1);

        jButton_lva_löschen.setText("Ausgewählte LVA Löschen");
        jButton_lva_löschen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_lva_löschenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jTable_list_lva_deleteLayout = new javax.swing.GroupLayout(jTable_list_lva_delete);
        jTable_list_lva_delete.setLayout(jTable_list_lva_deleteLayout);
        jTable_list_lva_deleteLayout.setHorizontalGroup(
            jTable_list_lva_deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTable_list_lva_deleteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_lva_löschen)
                .addGap(749, 749, 749))
        );
        jTable_list_lva_deleteLayout.setVerticalGroup(
            jTable_list_lva_deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTable_list_lva_deleteLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jTable_list_lva_deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jTable_list_lva_deleteLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jButton_lva_löschen, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("LVA Löschen", jTable_list_lva_delete);

        jTable_list_lva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "LVA Name", "LVA ID", "LVA Gruppe ", "Dozent Name"
            }
        ));
        jScrollPane1.setViewportView(jTable_list_lva);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Existierende LVA", jPanel1);

        jLabel4.setText("Gesamte Lehrstunde");

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel6.setText("Anwesenheitstabelle Ändern");

        jTextField_gesamte_lehrstunde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_gesamte_lehrstundeActionPerformed(evt);
            }
        });

        jButton1.setText("Lehrstunde Aktualisieren");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jToggleButton_loesche_alle_daten.setText("Lösche alle Daten");
        jToggleButton_loesche_alle_daten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_loesche_alle_datenActionPerformed(evt);
            }
        });

        jToggleButton2.setText("Lösche Daten des Datums");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel4)
                .addGap(50, 50, 50)
                .addComponent(jLabel_gesamt_lehrstunde, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(jTextField_gesamte_lehrstunde, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jButton1)
                .addGap(85, 85, 85))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton_loesche_alle_daten, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(278, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_gesamt_lehrstunde, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jTextField_gesamte_lehrstunde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)))
                .addGap(62, 62, 62)
                .addComponent(jLabel6)
                .addGap(37, 37, 37)
                .addComponent(jToggleButton_loesche_alle_daten)
                .addGap(40, 40, 40)
                .addComponent(jToggleButton2)
                .addContainerGap(225, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eigenschaften", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_check_con)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_con_state, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jInternalFrame_LVA_hinzufügen, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(740, 740, 740))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jInternalFrame_LVA_hinzufügen, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(362, 362, 362))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_check_con)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel_con_state, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void refresh_table(){
        DBconnect connect = new DBconnect();
        Vector<LVA> v = connect.get_all_lva();
         
        Dozent d = null;
        GRUPPE g = null;
        DefaultTableModel model = (DefaultTableModel)jTable_list_lva1.getModel();
        model.getDataVector().removeAllElements();
        for(int c = 0; c < v.size();c++){
            d = connect.get_DozentData(v.elementAt(c).getDozent_ID());
            g = connect.get_gruppe(v.elementAt(c).getGruppe_id());
            model.addRow(new Object[]{v.elementAt(c).getLVAname(),v.elementAt(c).getLVAid(),g.get_gruppe_name(),d.getDozentName()+" "+d.getDozentNachname()});
        } 
        model = (DefaultTableModel)jTable_list_lva.getModel();
        model.getDataVector().removeAllElements();
        for(int c = 0; c < v.size();c++){
            d = connect.get_DozentData(v.elementAt(c).getDozent_ID());
            g = connect.get_gruppe(v.elementAt(c).getGruppe_id());
            model.addRow(new Object[]{v.elementAt(c).getLVAname(),v.elementAt(c).getLVAid(),g.get_gruppe_name(),d.getDozentName()+" "+d.getDozentNachname()});
         }      
    }
   
    public String get_date(){
        String str = ((JTextField)jDateChooser_eigenschaften.getDateEditor().getUiComponent()).getText();
        System.out.println(str);
        return str;
    }
    
    public int split_combobox_data(String s){
        int i;
        String a[] = s.split(":");
        i = Integer.parseInt(a[1]);
        return i;
    }
    public String split_combobox_data_str(String s){
        int i;
        String a[] = s.split(":");
        return a[1];
    }
    public void fill_combobox(){  // Erfüllen der Comoboxes
        jComboBox_dozent_name.removeAllItems();
        jComboBox_gruppe_auswahl.removeAllItems();
        DBconnect connect = new DBconnect();
        Vector<Dozent> v = connect.get_all_DozentData();
        Vector<GRUPPE> v2 = connect.get_all_gruppe();
        for(int c = 0; c < v.size() ; c++){
            jComboBox_dozent_name.addItem(v.elementAt(c).getDozentName()+" "+v.elementAt(c).getDozentNachname()+":"+v.elementAt(c).getDozent_ID());  
        }
        for(int c = 0; c < v2.size() ; c++){
            jComboBox_gruppe_auswahl.addItem(v2.elementAt(c).get_gruppe_name()+":"+v2.elementAt(c).get_gruppe_id());
        }
    }
    private void lva_loeschen(){
        DBconnect connect = new DBconnect();
        DefaultTableModel model = (DefaultTableModel)jTable_list_lva1.getModel();
        int selectedRowIndex = jTable_list_lva1.getSelectedRow();
        connect.delete_lva((int)model.getValueAt(selectedRowIndex,1));
    }
    private void anwesenheitsdata_loeschen(){
        DBconnect connect = new DBconnect();
        connect.truncate_anwesenheit_table();
    }
    public void lehrstunde_zeigen(){
        DBconnect connect = new DBconnect();       
        jLabel_gesamt_lehrstunde.setText(Integer.toString(connect.get_gesamte_lehrstunde()));
    }
    private void lva_hinzufügen(){
        DBconnect connect = new DBconnect();
        LVA lva = new LVA(jTextField_lva_name.getText(),split_combobox_data(jComboBox_gruppe_auswahl.getSelectedItem().toString()),split_combobox_data(jComboBox_dozent_name.getSelectedItem().toString()));
        connect.insert_lva(lva);
        if(connect.connection_state){
                JOptionPane.showMessageDialog(Jframe_ADMIN.this,"Erfolgreich Hinzugefügt" );                
        }
        else{
                JOptionPane.showMessageDialog(Jframe_ADMIN.this,"Abgesagt,kontrollieren Sie Ihre DB Verbindung" );
            }
        refresh_table();
    }
    private void delete_anwdata_date(){
        DBconnect connect = new DBconnect();
        Anwesenheit a = new Anwesenheit(0, get_date(), 1, true);
        connect.delete_selected_anwdata(a.get_Date().toString());
    }
    private void fill_gruppe_combobox(){
        
    }
    
    private void jButton_check_conActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_check_conActionPerformed
        DBconnect connect = new DBconnect();
        jLabel_con_state.setText(connect.connection_sucessfull);
    }//GEN-LAST:event_jButton_check_conActionPerformed

    private void jTextField_lva_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_lva_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_lva_nameActionPerformed

    private void jComboBox_gruppe_auswahlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_gruppe_auswahlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_gruppe_auswahlActionPerformed

    private void jComboBox_dozent_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_dozent_nameActionPerformed
        
    }//GEN-LAST:event_jComboBox_dozent_nameActionPerformed
   
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        lva_hinzufügen();
        /*DBconnect connect = new DBconnect();
        LVA lva = new LVA(jTextField_lva_name.getText(),split_combobox_data(jComboBox_gruppe_auswahl.getSelectedItem().toString()),split_combobox_data(jComboBox_dozent_name.getSelectedItem().toString()));
        connect.insert_lva(lva);
        if(connect.connection_state){
                JOptionPane.showMessageDialog(Jframe_ADMIN.this,"Erfolgreich Hinzugefügt" );                
        }
        else{
                JOptionPane.showMessageDialog(Jframe_ADMIN.this,"Abgesagt,kontrollieren Sie Ihre DB Verbindung" );
            }
        refresh_table();*/
        //System.out.println(split_combobox_data(jComboBox_dozent_name.getSelectedItem().toString()));                        
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void jButton_lva_löschenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_lva_löschenActionPerformed
       int dialogResult = JOptionPane.showConfirmDialog(null, "Sind Sie damit sicher ?");
       if(dialogResult == JOptionPane.YES_OPTION){
            lva_loeschen();
            refresh_table(); 
        }
              
    }//GEN-LAST:event_jButton_lva_löschenActionPerformed

    private void jTextField_gesamte_lehrstundeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_gesamte_lehrstundeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_gesamte_lehrstundeActionPerformed

    private void jToggleButton_loesche_alle_datenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_loesche_alle_datenActionPerformed
       int dialogResult = JOptionPane.showConfirmDialog(null, "Sind Sie damit sicher ?");
       if(dialogResult == JOptionPane.YES_OPTION){
        anwesenheitsdata_loeschen();
        }
        
    }//GEN-LAST:event_jToggleButton_loesche_alle_datenActionPerformed

    private void jTabbedPane1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTabbedPane1KeyPressed
        
    }//GEN-LAST:event_jTabbedPane1KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DBconnect connect = new DBconnect();
        connect.update_gesamte_lehrstunde(Integer.parseInt(jTextField_gesamte_lehrstunde.getText()));
        lehrstunde_zeigen();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        delete_anwdata_date();
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
                    
         /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jframe_ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jframe_ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jframe_ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jframe_ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jframe_ADMIN().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_check_con;
    private javax.swing.JButton jButton_lva_löschen;
    private javax.swing.JComboBox<String> jComboBox_dozent_name;
    private javax.swing.JComboBox<String> jComboBox_gruppe_auswahl;
    private javax.swing.JInternalFrame jInternalFrame_LVA_hinzufügen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_con_state;
    private javax.swing.JLabel jLabel_gesamt_lehrstunde;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable_list_lva;
    private javax.swing.JTable jTable_list_lva1;
    private javax.swing.JPanel jTable_list_lva_delete;
    private javax.swing.JTextField jTextField_gesamte_lehrstunde;
    private javax.swing.JTextField jTextField_lva_name;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton_loesche_alle_daten;
    // End of variables declaration//GEN-END:variables
    

}


